{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name | default (include "workflow-platform.fullname" .) }}
  labels:
    {{- include "workflow-platform.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
